apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beerstock-ns
  name: beerstock-api-dp
spec:
  selector:
    matchLabels:
      app: beerstock-api-pod
  replicas: 3
  template:
    metadata:
      namespace: beerstock-ns
      labels:
        app: beerstock-api-pod
    spec:
      containers:
        - name: beerstock-api-containers
          image: santunioni/beerstock_api:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: {name: database-config}


---

apiVersion: v1
kind: Service
metadata:
  namespace: beerstock-ns
  name: beerstock-api-svc
spec:
  type: NodePort
  selector:
    app: beerstock-api-dp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
